--- 
title: "The Doctrine of Justification"
author: "James Buchanan"
date: "1867"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    config:
      toc:
        scroll_highlight: yes
      fontsettings:
        theme: white
        family: serif
        size: 2
    includes:
      after_body: reftagger.html
always_allow_html: yes
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: ldweeks/justification-buchanan
description: "An Outline of its History in the Church and of its Exposition from Scripture"
---

# Preface {-}

The Deed, by which the \'Cunningham Lectureship\' was established in connection with the New College, requires that a certain number of Discourses shall be delivered, biennially, in the presence of the Principal, Professors, and Students; but provides also for the admission of non-professional hearers, should any such be disposed to attend. This provision seems to imply, that it was the wish of the liberal and enlightened Founder to make these Lectures useful beyond the College circle; and it may be held to indicate that they should be so constructed as to be suitable alike to an Academic and to a popular audience. It is necessary, therefore, to adapt the method of exposition to different classes, while the same truth in substance is proclaimed to all; and this may perhaps be best accomplished by presenting, in the body of the work, the substantial results of the inquiry, as one that is mainly directed to unfold the history, to explain the meaning, and to establish the truth, of a doctrine of Scripture; and reserving the processes by which these results have been attained, and the critical or controversial discussions by which they may be illustrated and defended, for Notes in an Appendix, containing such references to standard works, on each successive topic, as may serve to direct younger students to the best sources of information. The Notes are indicated by numerals inserted in the Text of each Lecture, which will be found to correspond with those in the Appendix. It has not been thought necessary to extend the Index beyond the body of the work, as the Notes in the Appendix are sufficiently indicated by the insertion of these numerals in the Text.

The topic for discussion in each series of the \'Cunningham Lectures\' is left to be selected by the Author, subject to the consent of the Council. For the second series, the Doctrine of Justification by Grace through Faith has been chosen, after much serious reflection. In treating this important subject, it is proposed to offer, both an outline of its History in the Church, and an outline also of its Exposition from Scripture. There are various methods of teaching Theology, but the most important are the Historical and the Logical. They are both systematic, but they are founded on two different relations subsisting between the truths of Scripture; the first,---on the relation of prior and posterior in respect to their chronological development,---the second, on the internal relation between them in respect to their doctrinal meaning, which arises from the fact that some truths necessarily presuppose certain other truths, and can neither be stated nor proved without reference to them. Each of these methods has some advantages which are peculiar to itself, and the combination of the two is necessary to any complete course of Theology. The one marks the successive unfoldings of divine truth, and the various controversies which have arisen in regard to it; the other, keeping in view the doctrinal results of that history, expounds the lessons of Scripture, in the light which has thus been shed upon them. Every great doctrine of Scripture might be treated in this way; and that of Justification having been selected, an outline of its History in the Church is given, as introductory to an outline of its Exposition from Scripture. The former only was delivered from the chair, as far as time permitted, and constitutes properly the second series of the \'Cunningham Lectures;\' the latter is offered as a sequel to it, which, it is hoped, will not be deemed unseasonable in the present critical times. From the nature of this complex plan, it was unavoidable that the same topics should occur more than once; but if they are presented in new aspects and relations, and applied in different ways, any instances of this kind can scarcely be regarded as mere repetitions. Cross references are occasionally inserted where the same topic Is lightly touched in one place, and more fully treated in another.
